service: sls-offline-api

provider:
  name: aws
  apiKeys:
    - name: ${opt:stage}-api-key
      value: ${opt:apiKey}
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100
  runtime: nodejs8.10

plugins:
  - serverless-offline

functions:
    anatomy:
      handler: anatomy-handler.anatomy
      events:
        - http: GET /

    publicHello:
      handler: public-handler.hello
      events:
        - http: GET hello
          request:
            parameters:
              paths:
                name: true

    privateHello:
      handler: private-handler.hello
      events:
        - http:
            path: hello/pvt
            method: get
            private: true

    postHandler:
      handler: post-handler.squarer
      events:
        - http:
            path: example
            method: POST
            cors:
              origin: '*'
              headers:
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - X-Amz-User-Agent
